# Write a function so that the columns of the output matrix are powers of the input vector. 
# The order of the powers is determined by the increasing boolean argument. Specifically, when  increasing is False, the i-th output column is the input vector raised element-wise to the power  of N - i - 1. 
####    HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde. 


In [1]:
import numpy as np

In [2]:
def generateMatrix(vector,cols,increase):
    if not increase:
        matrix = np.array([x**(cols-i-1) for x in vector for i in range(cols)]).reshape(vector.size,cols)
    else:
        matrix = np.array([x**(i) for x in vector for i in range(cols)]).reshape(vector.size,cols)
    return matrix

In [3]:
vector = [1,2,3,4]
cols = 3
finalMatrix = generateMatrix(np.array(vector),cols,False)

In [4]:
finalMatrix

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])

In [5]:
vector = [1,2,3,4]
cols = 3
finalMatrix = generateMatrix(np.array(vector),cols,True)

In [6]:
finalMatrix

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16]])

# Write a function to find moving average in an array over a window:  Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [7]:
def moving_avg(list,k):
    cumSum = np.cumsum(list)
    cumSum[k:] = cumSum[k:]-cumSum[:-k]
    return cumSum[k-1:]/k

In [8]:
a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k = 3

In [9]:
op = moving_avg(a,k)
op = np.array(op).round(1)

In [10]:
op

array([  5. ,   4.7,   5.7,   6.7,   9.7,  28.7,  49.3,  72.7,  84. ,
        93.3, 116.3])